# https://learn.microsoft.com/en-us/dotnet/devops/dotnet-test-github-action
name: build and test
on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'
jobs:
  build-chirp-razor:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      working-directory: src/Chirp.Web
      run: dotnet restore

    - name: Build
      working-directory: src/Chirp.Web
      run: dotnet build --configuration Release --no-restore

    - name: Chirp.Core tests
      working-directory: test/Chirp.Core.Tests
      run: dotnet test --no-restore --verbosity normal
      
    - name: Chirp.Infrastructure tests
      working-directory: test/Chirp.Infrastructure.Tests
      run: dotnet test --no-restore --verbosity normal

    - name: Chirp.Web tests
      working-directory: test/Chirp.Web.Tests
      run: dotnet test --no-restore --verbosity normal

    - name: Chirp.Core.Utils test
      working-directory: test/Chirp.Utils.Tests
      run: dotnet test --no-restore --verbosity normal


